# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '12.0'
use_frameworks!

workspace 'Hoof.xcworkspace'

def shared_pods
  pod 'CoreGPX'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
end

def shared_UIPods
  pod "DrawerView"
end

# Common modules
target 'Core' do
  project 'Common/Core/Core'
  shared_pods
end

# Feature modules
target 'Home' do
  project 'Features/Home/Home'
  shared_pods
  
  target 'HomeTests' do
    inherit! :search_paths
    shared_pods
  end
end

target 'Map' do
  project 'Features/Map/Map'
  shared_pods
  shared_UIPods
  
  target 'MapTests' do
    inherit! :search_paths
    shared_pods
  end
end

target 'Groups' do
  project 'Features/Groups/Groups'
  shared_pods
  
  target 'GroupsTests' do
    inherit! :search_paths
    shared_pods
  end
end

target 'Profile' do
  project 'Features/Profile/Profile'
  shared_pods
  
  target 'ProfileTests' do
    inherit! :search_paths
    shared_pods
  end
end

target 'CreateChallenge' do
  project 'Features/CreateChallenge/CreateChallenge'
  shared_pods
  
  target 'CreateChallengeTests' do
    inherit! :search_paths
    shared_pods
  end
end

target 'Welcome' do
  project 'Features/Welcome/Welcome'
  shared_pods
  
  target 'WelcomeTests' do
    inherit! :search_paths
    shared_pods
  end
end

target 'SignUp' do
  project 'Features/SignUp/SignUp'
  shared_pods
  
  target 'SignUpTests' do
    inherit! :search_paths
    shared_pods
  end
end

# Apps
target 'Hoof' do
  # Pods for Hoof
  shared_pods
  shared_UIPods
  pod 'MapCache', '~> 0.9.0'
  
  target 'HoofTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end
  
  target 'HoofUITests' do
    # Pods for testing
  end
  
end

target 'WatchHoof' do
  # Pods for WatchHoof
  
  target 'WatchHoofTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'WatchHoofUITests' do
    # Pods for testing
  end
  
end

target 'WatchHoof Extension' do
  
  # Pods for WatchHoof Extension
  platform :watchos, '2.0'
  shared_pods
  
end
